def footer(index_file):
    footer_template = '''<p class="text-info">Generated by <a href="https://github.com/kaustubhgupta">Kaustubh Gupta</a></p>'''
    replacement = index_file.replace("<!-- FOOTER-ENTRY -->", footer_template)
    return replacement